#!/bin/bash

LIST=".i3/config .i3status.conf .spacemacs .bash_aliases .zshrc .tmux.conf .atom/package.list .atom/config.cson .atom/keymap.cson .atom/snippets.cson .chunkwmrc .skhdrc"

if [ "$1" == "up" ]
then
    echo "putting files into ~/"
    for I in $LIST; do
        echo "Copying file $I"
	      cp -R $I ~/$I
    done

    echo "syncing atom"
    apm install --packages-file $HOME/.atom/package.list
elif [ "$1" == "down"  ]
then
    echo "Saving atom packages..."
    apm list --installed --bare > $HOME/.atom/package.list

    echo "Copying files from ~/"
    for I in  $LIST; do
        echo "Copying file $I"
        cp -R ~/$I $I
    done
else
    echo "Usage: ./dotfiles [command]"
    echo "Commands:"
    echo "    up - will put files into ~/"
    echo "    down - will copy files from ~/"
fi
